### ISSUE TITLE
Exception handling when user cancels login authorization from social media

### ISSUE THREAD

**Issue by rkthakur** [rkthakur/mediamixmodeling#21]
FacebookAuthorizationError: User canceled the Dialog flow
   at Strategy.authenticate (/Users/rthaku/Personal/Google_Drive/Sapient/CMTOu/MTP/repo/mediamixmodeling/reportInterface/mmmdash/node_modules/passport-facebook/lib/strategy.js:79:23)
   at attempt (/Users/rthaku/Personal/Google_Drive/Sapient/CMTOu/MTP/repo/mediamixmodeling/reportInterface/mmmdash/node_modules/passport/lib/middleware/authenticate.js:348:16)
   at Object.authenticate [as handle](/Users/rthaku/Personal/Google_Drive/Sapient/CMTOu/MTP/repo/mediamixmodeling/reportInterface/mmmdash/node_modules/passport/lib/middleware/authenticate.js:349:7)
   at next_layer (/Users/rthaku/Personal/Google_Drive/Sapient/CMTOu/MTP/repo/mediamixmodeling/reportInterface/mmmdash/node_modules/express/lib/router/route.js:113:13)
   at Route.dispatch (/Users/rthaku/Personal/Google_Drive/Sapient/CMTOu/MTP/repo/mediamixmodeling/reportInterface/mmmdash/node_modules/express/lib/router/route.js:117:5)
   at /Users/rthaku/Personal/Google_Drive/Sapient/CMTOu/MTP/repo/mediamixmodeling/reportInterface/mmmdash/node_modules/express/lib/router/index.js:222:24
   at Function.proto.process_params (/Users/rthaku/Personal/Google_Drive/Sapient/CMTOu/MTP/repo/mediamixmodeling/reportInterface/mmmdash/node_modules/express/lib/router/index.js:288:12)
   at next (/Users/rthaku/Personal/Google_Drive/Sapient/CMTOu/MTP/repo/mediamixmodeling/reportInterface/mmmdash/node_modules/express/lib/router/index.js:216:19)
   at

**Comment by abhishek-net** [comment]
Earphone order kijiye wrna mai nahi kr rha kch waise hi halat kharab hai

Regards,
Abhishek Mishra

**Comment by abhishek-net** [comment]
Invalid issue.
